// ═══════════════════════════════════════════════════════════════════
// DEFAULT EXERCISE LIBRARY — ships with the app for every new user
// Grouped by muscle group in display order:
//   Chest → Legs → Arms → Back → Shoulders → Abs
// ═══════════════════════════════════════════════════════════════════

const DEFAULT_EXERCISES = [
    // ═══════════════════════════════════════
    // CHEST
    // ═══════════════════════════════════════
    ['Barbell Bench Press', 'chest', 'Barbell'],
    ['Dumbbell Bench Press', 'chest', 'Dumbbell'],
    ['Smith Machine Bench Press', 'chest', 'Machine'],
    ['Machine Chest Press', 'chest', 'Machine'],
    ['Incline Barbell Bench Press', 'chest', 'Barbell'],
    ['Incline Dumbbell Bench Press', 'chest', 'Dumbbell'],
    ['Incline Smith Machine Bench Press', 'chest', 'Machine'],
    ['Incline Machine Chest Press', 'chest', 'Machine'],
    ['Decline Barbell Bench Press', 'chest', 'Barbell'],
    ['Decline Dumbbell Bench Press', 'chest', 'Dumbbell'],
    ['Decline Smith Machine Bench Press', 'chest', 'Machine'],
    ['Decline Machine Chest Press', 'chest', 'Machine'],
    ['Dumbbell Fly (Flat)', 'chest', 'Dumbbell'],
    ['Incline Dumbbell Fly', 'chest', 'Dumbbell'],
    ['Decline Dumbbell Fly', 'chest', 'Dumbbell'],
    ['Cable Fly (Standing)', 'chest', 'Cable'],
    ['Cable Fly (Seated)', 'chest', 'Cable'],
    ['Low-To-High Cable Fly', 'chest', 'Cable'],
    ['High-To-Low Cable Fly', 'chest', 'Cable'],
    ['Pec Deck Fly', 'chest', 'Machine'],
    ['Reverse-Grip Bench Press', 'chest', 'Barbell'],
    ['Close-Grip Bench Press (Chest/Triceps)', 'chest', 'Barbell'],
    ['Push-Up (Standard)', 'chest', 'Bodyweight'],
    ['Incline Push-Up', 'chest', 'Bodyweight'],
    ['Decline Push-Up', 'chest', 'Bodyweight'],
    ['Close-Grip Push-Up', 'chest', 'Bodyweight'],
    ['Chest Dips (Weighted/Assisted)', 'chest', 'Bodyweight'],
    ['Dumbbell Pullover', 'chest', 'Dumbbell'],
    ['Cable Press (Standing)', 'chest', 'Cable'],
    ['Single-Arm Cable Press', 'chest', 'Cable'],
    ['Resistance Band Chest Press', 'chest', 'Band'],
    ['Plate Press (Svend Press)', 'chest', 'Bodyweight'],
    ['Paused Bench Press', 'chest', 'Barbell'],
    ['Spoto Press', 'chest', 'Barbell'],
    ['Feet-Up Bench Press', 'chest', 'Barbell'],
    ['Ring Push-Up (Advanced)', 'chest', 'Bodyweight'],

    // ═══════════════════════════════════════
    // LEGS
    // ═══════════════════════════════════════
    // Compounds / Quads
    ['Back Squat', 'legs', 'Barbell'],
    ['Front Squat', 'legs', 'Barbell'],
    ['Goblet Squat', 'legs', 'Dumbbell'],
    ['Smith Machine Squat', 'legs', 'Machine'],
    ['Hack Squat (Machine)', 'legs', 'Machine'],
    ['Leg Press (Machine)', 'legs', 'Machine'],
    ['Narrow-Stance Leg Press (Quad Bias)', 'legs', 'Machine'],
    ['High-Foot Leg Press (Glute Bias)', 'legs', 'Machine'],
    ['Bulgarian Split Squat', 'legs', 'Dumbbell'],
    ['Split Squat', 'legs', 'Bodyweight'],
    ['Walking Lunge', 'legs', 'Dumbbell'],
    ['Reverse Lunge', 'legs', 'Dumbbell'],
    ['Forward Lunge', 'legs', 'Dumbbell'],
    ['Static Lunge', 'legs', 'Bodyweight'],
    ['Step-Up', 'legs', 'Dumbbell'],
    ['Heels-Elevated Squat', 'legs', 'Barbell'],
    ['Cyclist Squat', 'legs', 'Dumbbell'],
    ['Belt Squat (Machine)', 'legs', 'Machine'],
    ['Landmine Squat', 'legs', 'Barbell'],
    ['Leg Extension (Machine)', 'legs', 'Machine'],
    ['Single-Leg Leg Extension', 'legs', 'Machine'],
    ['Sissy Squat (Bodyweight/Machine)', 'legs', 'Bodyweight'],
    // Hamstrings / Posterior Chain
    ['Romanian Deadlift (Barbell)', 'legs', 'Barbell'],
    ['Romanian Deadlift (Dumbbell)', 'legs', 'Dumbbell'],
    ['Stiff-Leg Deadlift', 'legs', 'Barbell'],
    ['Conventional Deadlift', 'legs', 'Barbell'],
    ['Sumo Deadlift', 'legs', 'Barbell'],
    ['Trap Bar Deadlift', 'legs', 'Barbell'],
    ['Good Morning', 'legs', 'Barbell'],
    ['Cable Pull-Through', 'legs', 'Cable'],
    ['Lying Leg Curl (Machine)', 'legs', 'Machine'],
    ['Seated Leg Curl (Machine)', 'legs', 'Machine'],
    ['Standing Leg Curl (Machine)', 'legs', 'Machine'],
    ['Nordic Hamstring Curl (Assisted)', 'legs', 'Bodyweight'],
    ['Glute-Ham Raise (GHR)', 'legs', 'Bodyweight'],
    ['Single-Leg Romanian Deadlift', 'legs', 'Dumbbell'],
    ['Kettlebell Swing', 'legs', 'Dumbbell'],
    // Glutes / Hips
    ['Barbell Hip Thrust', 'legs', 'Barbell'],
    ['Machine Hip Thrust', 'legs', 'Machine'],
    ['Barbell Glute Bridge', 'legs', 'Barbell'],
    ['Glute Bridge (Bodyweight)', 'legs', 'Bodyweight'],
    ['Cable Glute Kickback', 'legs', 'Cable'],
    ['Machine Glute Kickback', 'legs', 'Machine'],
    ['Hip Abduction Machine', 'legs', 'Machine'],
    ['Hip Adduction Machine', 'legs', 'Machine'],
    ['Banded Lateral Walk', 'legs', 'Band'],
    ['Clamshell (Band)', 'legs', 'Band'],
    ['Frog Pumps', 'legs', 'Bodyweight'],
    ['Reverse Hyperextension (Machine)', 'legs', 'Machine'],
    ['45 Degree Back Extension (Glute Focus)', 'legs', 'Bodyweight'],
    // Calves / Tibialis
    ['Standing Calf Raise (Machine)', 'legs', 'Machine'],
    ['Standing Calf Raise (Smith Machine)', 'legs', 'Machine'],
    ['Standing Calf Raise (Dumbbell)', 'legs', 'Dumbbell'],
    ['Seated Calf Raise (Machine)', 'legs', 'Machine'],
    ['Donkey Calf Raise', 'legs', 'Machine'],
    ['Leg Press Calf Press', 'legs', 'Machine'],
    ['Single-Leg Calf Raise (Bodyweight)', 'legs', 'Bodyweight'],
    ['Tibialis Raise (Machine/Bodyweight)', 'legs', 'Bodyweight'],

    // ═══════════════════════════════════════
    // ARMS
    // ═══════════════════════════════════════
    // Biceps
    ['Barbell Curl', 'arms', 'Barbell'],
    ['EZ-Bar Curl', 'arms', 'Barbell'],
    ['Dumbbell Curl', 'arms', 'Dumbbell'],
    ['Alternating Dumbbell Curl', 'arms', 'Dumbbell'],
    ['Hammer Curl', 'arms', 'Dumbbell'],
    ['Cross-Body Hammer Curl', 'arms', 'Dumbbell'],
    ['Incline Dumbbell Curl', 'arms', 'Dumbbell'],
    ['Preacher Curl (EZ-Bar)', 'arms', 'Barbell'],
    ['Preacher Curl (Dumbbell)', 'arms', 'Dumbbell'],
    ['Machine Preacher Curl', 'arms', 'Machine'],
    ['Cable Curl (Straight Bar)', 'arms', 'Cable'],
    ['Cable Curl (Rope)', 'arms', 'Cable'],
    ['Single-Arm Cable Curl', 'arms', 'Cable'],
    ['Spider Curl', 'arms', 'Dumbbell'],
    ['Concentration Curl', 'arms', 'Dumbbell'],
    ['Bayesian Cable Curl', 'arms', 'Cable'],
    ['Reverse Curl (Barbell/EZ-Bar)', 'arms', 'Barbell'],
    ['Zottman Curl', 'arms', 'Dumbbell'],
    ['Chin-Up (Biceps Emphasis)', 'arms', 'Bodyweight'],
    ['Machine Biceps Curl', 'arms', 'Machine'],
    // Triceps
    ['Close-Grip Bench Press', 'arms', 'Barbell'],
    ['Bench Dip', 'arms', 'Bodyweight'],
    ['Parallel Bar Dip (Triceps Bias)', 'arms', 'Bodyweight'],
    ['Cable Triceps Pushdown (Straight Bar)', 'arms', 'Cable'],
    ['Cable Triceps Pushdown (Rope)', 'arms', 'Cable'],
    ['Cable Triceps Pushdown (V-Bar)', 'arms', 'Cable'],
    ['Overhead Cable Triceps Extension (Rope)', 'arms', 'Cable'],
    ['Overhead Dumbbell Triceps Extension', 'arms', 'Dumbbell'],
    ['Skull Crushers (EZ-Bar)', 'arms', 'Barbell'],
    ['Skull Crushers (Dumbbell)', 'arms', 'Dumbbell'],
    ['Lying Triceps Extension (Barbell)', 'arms', 'Barbell'],
    ['Tate Press', 'arms', 'Dumbbell'],
    ['Triceps Kickback (Dumbbell)', 'arms', 'Dumbbell'],
    ['Single-Arm Cable Pushdown', 'arms', 'Cable'],
    ['Single-Arm Overhead Cable Extension', 'arms', 'Cable'],
    ['Machine Triceps Extension', 'arms', 'Machine'],
    ['Diamond Push-Up', 'arms', 'Bodyweight'],
    ['JM Press (Advanced)', 'arms', 'Barbell'],
    // Forearms / Grip
    ['Wrist Curl (Dumbbell)', 'arms', 'Dumbbell'],
    ['Wrist Curl (Barbell)', 'arms', 'Barbell'],
    ['Reverse Wrist Curl', 'arms', 'Dumbbell'],
    ['Cable Wrist Curl', 'arms', 'Cable'],
    ['Wrist Roller', 'arms', 'Bodyweight'],
    ['Farmer Carry (Dumbbell/Trap Bar)', 'arms', 'Dumbbell'],
    ['Plate Pinch Hold', 'arms', 'Bodyweight'],
    ['Dead Hang (Pull-Up Bar)', 'arms', 'Bodyweight'],
    ['Towel Dead Hang', 'arms', 'Bodyweight'],

    // ═══════════════════════════════════════
    // BACK
    // ═══════════════════════════════════════
    // Vertical Pull (Lats)
    ['Pull-Up', 'back', 'Bodyweight'],
    ['Chin-Up', 'back', 'Bodyweight'],
    ['Assisted Pull-Up', 'back', 'Machine'],
    ['Lat Pulldown (Wide Grip)', 'back', 'Cable'],
    ['Lat Pulldown (Close Grip)', 'back', 'Cable'],
    ['Neutral-Grip Lat Pulldown', 'back', 'Cable'],
    ['Underhand Lat Pulldown', 'back', 'Cable'],
    ['Single-Arm Lat Pulldown', 'back', 'Cable'],
    ['Straight-Arm Cable Pulldown', 'back', 'Cable'],
    ['Machine Pulldown', 'back', 'Machine'],
    // Horizontal Row (Mid Back)
    ['Barbell Row', 'back', 'Barbell'],
    ['Pendlay Row', 'back', 'Barbell'],
    ['One-Arm Dumbbell Row', 'back', 'Dumbbell'],
    ['Chest-Supported Dumbbell Row', 'back', 'Dumbbell'],
    ['T-Bar Row', 'back', 'Barbell'],
    ['Chest-Supported T-Bar Row', 'back', 'Machine'],
    ['Seated Cable Row (V-Grip)', 'back', 'Cable'],
    ['Seated Cable Row (Wide Grip)', 'back', 'Cable'],
    ['Single-Arm Seated Cable Row', 'back', 'Cable'],
    ['Machine Row (Plate-Loaded)', 'back', 'Machine'],
    ['Smith Machine Row', 'back', 'Machine'],
    ['Inverted Row (Bodyweight)', 'back', 'Bodyweight'],
    // Upper Back / Traps / Rear Delt Support
    ['Face Pull (Cable)', 'back', 'Cable'],
    ['Reverse Pec Deck (Rear Delt Fly)', 'back', 'Machine'],
    ['Rear Delt Dumbbell Fly', 'back', 'Dumbbell'],
    ['Cable Rear Delt Fly', 'back', 'Cable'],
    ['Barbell Shrug', 'back', 'Barbell'],
    ['Dumbbell Shrug', 'back', 'Dumbbell'],
    ['Smith Machine Shrug', 'back', 'Machine'],
    ['Scapular Pull-Up', 'back', 'Bodyweight'],
    // Lower Back / Erectors
    ['Back Extension (45 Degree)', 'back', 'Bodyweight'],
    ['Hyperextension (Roman Chair)', 'back', 'Bodyweight'],
    ['Reverse Hyperextension', 'back', 'Machine'],
    ['Good Morning (Back)', 'back', 'Barbell'],
    ['Deadlift (Conventional)', 'back', 'Barbell'],
    ['Romanian Deadlift (Back)', 'back', 'Barbell'],
    ['Superman Hold', 'back', 'Bodyweight'],
    ['Bird Dog', 'back', 'Bodyweight'],

    // ═══════════════════════════════════════
    // SHOULDERS
    // ═══════════════════════════════════════
    // Pressing (Delts)
    ['Overhead Press (Barbell)', 'shoulders', 'Barbell'],
    ['Seated Overhead Press (Barbell)', 'shoulders', 'Barbell'],
    ['Dumbbell Shoulder Press', 'shoulders', 'Dumbbell'],
    ['Seated Dumbbell Shoulder Press', 'shoulders', 'Dumbbell'],
    ['Machine Shoulder Press', 'shoulders', 'Machine'],
    ['Smith Machine Overhead Press', 'shoulders', 'Machine'],
    ['Arnold Press', 'shoulders', 'Dumbbell'],
    ['Push Press (Advanced)', 'shoulders', 'Barbell'],
    ['Landmine Press', 'shoulders', 'Barbell'],
    ['Single-Arm Landmine Press', 'shoulders', 'Barbell'],
    // Lateral / Medial Delt
    ['Dumbbell Lateral Raise', 'shoulders', 'Dumbbell'],
    ['Cable Lateral Raise', 'shoulders', 'Cable'],
    ['Machine Lateral Raise', 'shoulders', 'Machine'],
    ['Seated Lateral Raise', 'shoulders', 'Dumbbell'],
    ['Lean-Away Cable Lateral Raise', 'shoulders', 'Cable'],
    ['Behind-The-Back Cable Lateral Raise', 'shoulders', 'Cable'],
    // Front Delt
    ['Dumbbell Front Raise', 'shoulders', 'Dumbbell'],
    ['Cable Front Raise', 'shoulders', 'Cable'],
    ['Plate Front Raise', 'shoulders', 'Bodyweight'],
    ['Incline Front Raise', 'shoulders', 'Dumbbell'],
    // Rear Delt / Stability
    ['Rear Delt Fly (Dumbbell)', 'shoulders', 'Dumbbell'],
    ['Reverse Pec Deck (Rear Delt)', 'shoulders', 'Machine'],
    ['Cable Rear Delt Fly (Shoulders)', 'shoulders', 'Cable'],
    ['Face Pull', 'shoulders', 'Cable'],
    ['Band Pull-Apart', 'shoulders', 'Band'],
    ['Y-Raise (Incline Bench)', 'shoulders', 'Dumbbell'],
    ['External Rotation (Cable/Band)', 'shoulders', 'Cable'],
    ['Cuban Rotation (Light/Controlled)', 'shoulders', 'Dumbbell'],
    // Traps (often trained with shoulders)
    ['Farmer Carry', 'shoulders', 'Dumbbell'],
    ['Dumbbell Shrug (Shoulders)', 'shoulders', 'Dumbbell'],

    // ═══════════════════════════════════════
    // ABS
    // ═══════════════════════════════════════
    // Core Flexion
    ['Crunch (Floor)', 'abs', 'Bodyweight'],
    ['Cable Crunch (Kneeling)', 'abs', 'Cable'],
    ['Machine Crunch', 'abs', 'Machine'],
    ['Decline Crunch', 'abs', 'Bodyweight'],
    ['Reverse Crunch', 'abs', 'Bodyweight'],
    ['Toe Touch Crunch', 'abs', 'Bodyweight'],
    // Leg Raise Variations
    ['Hanging Leg Raise', 'abs', 'Bodyweight'],
    ['Hanging Knee Raise', 'abs', 'Bodyweight'],
    ['Captain Chair Leg Raise', 'abs', 'Machine'],
    ['Lying Leg Raise', 'abs', 'Bodyweight'],
    ['Garhammer Raise', 'abs', 'Bodyweight'],
    // Stability / Anti-Extension
    ['Plank', 'abs', 'Bodyweight'],
    ['Side Plank', 'abs', 'Bodyweight'],
    ['RKC Plank', 'abs', 'Bodyweight'],
    ['Ab Wheel Rollout (Kneeling)', 'abs', 'Bodyweight'],
    ['Ab Wheel Rollout (Standing) (Advanced)', 'abs', 'Bodyweight'],
    ['Stability Ball Rollout', 'abs', 'Bodyweight'],
    ['Dead Bug', 'abs', 'Bodyweight'],
    ['Hollow Body Hold', 'abs', 'Bodyweight'],
    ['Body Saw (TRX/Sliders)', 'abs', 'Bodyweight'],
    // Anti-Rotation / Obliques
    ['Pallof Press (Cable)', 'abs', 'Cable'],
    ['Cable Woodchop (High-To-Low)', 'abs', 'Cable'],
    ['Cable Woodchop (Low-To-High)', 'abs', 'Cable'],
    ['Russian Twist (Bodyweight/Plate)', 'abs', 'Bodyweight'],
    ['Bicycle Crunch', 'abs', 'Bodyweight'],
    ['Dumbbell Side Bend', 'abs', 'Dumbbell'],
    ['Cable Side Bend', 'abs', 'Cable'],
    ['Suitcase Carry', 'abs', 'Dumbbell'],
    ['Landmine Rotation', 'abs', 'Barbell'],
    // Total Core / Conditioning
    ['Mountain Climbers', 'abs', 'Bodyweight'],
    ['V-Up', 'abs', 'Bodyweight'],
    ['Flutter Kicks', 'abs', 'Bodyweight'],
    ['Scissor Kicks', 'abs', 'Bodyweight'],
    ['Hanging Windshield Wipers (Advanced)', 'abs', 'Bodyweight'],
];

export default DEFAULT_EXERCISES;
